In [244]:
#Intro Numpy

In [245]:
import numpy as np
np.__version__

'1.16.4'

In [246]:
# Initiate GPA with list of values
GPA = [4.0, 3.2, 3.69, 3.92]
GPA

[4.0, 3.2, 3.69, 3.92]

In [247]:
# Add new GPA data to the end of the list
GPA.append(3.95)
GPA

[4.0, 3.2, 3.69, 3.92, 3.95]

In [248]:
# Initialize study_minutes with 100s zeros using np.zeros
# We are only storing positive values and zeros so we are using unsigned-int16.
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [249]:
# %whos: A special Jupyter Notebook command
%whos

Variable             Type           Data/Info
---------------------------------------------
GPA                  list           n=5
GPAS                 ndarray        5: 5 elems, type `float64`, 40 bytes
fake_log             ndarray        100: 100 elems, type `uint16`, 200 bytes
first_day_minutes    uint16         170
fourth_day_minutes   uint16         60
index                ndarray        2x2: 4 elems, type `int64`, 32 bytes
np                   module         <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
rand                 RandomState    <mtrand.RandomState object at 0x111a7ae58>
second_day_minutes   uint16         75
students_gpas        ndarray        3x4: 12 elems, type `float16`, 24 bytes
study_minutes        ndarray        100: 100 elems, type `uint16`, 200 bytes
third_day_minutes    uint16         44


In [250]:
# Add data to the top of the list
study_minutes[0] = 170

In [251]:
first_day_minutes = study_minutes[0]
first_day_minutes

170

In [252]:
# Add data to the second on the lsit
study_minutes[1] = 75
second_day_minutes = study_minutes[1]
second_day_minutes

75

In [253]:
study_minutes[2] = 44
third_day_minutes = study_minutes[2]
third_day_minutes

44

In [254]:
study_minutes[3] = 60
fourth_day_minutes = study_minutes[3]
fourth_day_minutes

60

In [255]:
# Create n-dimensional array
students_gpas = np.array([
    [4.3, 3.23, 3.69, 3.92],
    [3.72, 2.2, 3.74, 3.89],
    [2.0, 3.44, 3.69, 4.0]
], np.float16)
students_gpas

array([[4.3 , 3.23, 3.69, 3.92],
       [3.72, 2.2 , 3.74, 3.89],
       [2.  , 3.44, 3.69, 4.  ]], dtype=float16)

In [256]:
# 2 dimensional - Rows * Columns
students_gpas.ndim

2

In [257]:
# Matrix shape. X-axis(rows) and Y-axis(column)
students_gpas.shape

(3, 4)

In [258]:
# All of the total element
students_gpas.size

12

In [259]:
# Total student... rows
len(students_gpas)

3

In [260]:
# %whos: A special Jupyter Notebook command
%whos ndarray

Variable        Type       Data/Info
------------------------------------
GPAS            ndarray    5: 5 elems, type `float64`, 40 bytes
fake_log        ndarray    100: 100 elems, type `uint16`, 200 bytes
index           ndarray    2x2: 4 elems, type `int64`, 32 bytes
students_gpas   ndarray    3x4: 12 elems, type `float16`, 24 bytes
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [261]:
# NumPy special command for info ~%whos
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7feaa2d9ff80
byteorder:  little
byteswap:  False
type: float16


In [262]:
# Access a particular student GPA
students_gpas[2]

array([2.  , 3.44, 3.69, 4.  ], dtype=float16)

In [263]:
# Create 2nd dim array
study_minutes = np.array([
    
    study_minutes,
    np.zeros(100, np.uint16)
])
study_minutes.shape

(2, 100)

In [264]:
# Add a data to the 2nd dim array. 
study_minutes[1][0] = 90 #[1] for the 2nd array, and [0] for the first array of second array.
study_minutes

array([[170,  75,  44,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [265]:
# Another way to add data in N-DIM array
# Its just a Tuple[(1,1)]
study_minutes[1,1] = 75 # same as study_minutes[1][1] = 60
study_minutes

array([[170,  75,  44,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 90,  75,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [266]:
# Random number generator
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log
fake_log[[3,8]]

array([44, 50], dtype=uint16)

In [267]:
index = np.array([
    [3,8],
    [0,1]
])

fake_log[index]

array([[ 44,  50],
       [132, 122]], dtype=uint16)

In [268]:
# Append fake_log data into study_minutes
study_minutes = np.append(study_minutes, [fake_log], axis=0)

In [270]:
study_minutes[1,2] = 65
study_minutes

array([[170,  75,  44,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 90,  75,  65,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [273]:
fake_log > 60

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True])

In [275]:
fake_log[fake_log > 30]

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [284]:
study_minutes[(study_minutes < 60) & (study_minutes > 0)]

array([44, 44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52,
       31, 57, 37, 58], dtype=uint16)

In [290]:
np.array([True, False, True]) & np.array([False, False, True])

array([False, False,  True])