In [118]:
#Intro Numpy

In [119]:
import numpy as np
np.__version__

'1.16.4'

In [120]:
# Initiate GPA with list of values
GPA = [4.0, 3.2, 3.69, 3.92]
GPA

[4.0, 3.2, 3.69, 3.92]

In [121]:
# Add new GPA data to the end of the list
GPA.append(3.95)
GPA

[4.0, 3.2, 3.69, 3.92, 3.95]

In [122]:
# Initialize study_minutes with 100s zeros using np.zeros
# We are only storing positive values and zeros so we are using unsigned-int16.
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [123]:
# %whos: A special Jupyter Notebook command
%whos

Variable             Type       Data/Info
-----------------------------------------
GPA                  list       n=5
GPAS                 ndarray    5: 5 elems, type `float64`, 40 bytes
first_day_minutes    uint16     170
np                   module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
second_day_minutes   uint16     75
students_gpas        ndarray    3x4: 12 elems, type `float16`, 24 bytes
study_minutes        ndarray    100: 100 elems, type `uint16`, 200 bytes


In [124]:
# Add data to the top of the list
study_minutes[0] = 170

In [125]:
first_day_minutes = study_minutes[0]
first_day_minutes

170

In [126]:
# Add data to the second on the lsit
study_minutes[1] = 75

In [127]:
second_day_minutes = study_minutes[1]
second_day_minutes

75

In [128]:
# Create n-dimensional array
students_gpas = np.array([
    [4.3, 3.23, 3.69, 3.92],
    [3.72, 2.2, 3.74, 3.89],
    [2.0, 3.44, 3.69, 4.0]
], np.float16)
students_gpas

array([[4.3 , 3.23, 3.69, 3.92],
       [3.72, 2.2 , 3.74, 3.89],
       [2.  , 3.44, 3.69, 4.  ]], dtype=float16)

In [129]:
# 2 dimensional - Rows * Columns
students_gpas.ndim

2

In [130]:
# Matrix shape. X-axis(rows) and Y-axis(column)
students_gpas.shape

(3, 4)

In [131]:
# All of the total element
students_gpas.size

12

In [132]:
# Total student... rows
len(students_gpas)

3

In [133]:
# %whos: A special Jupyter Notebook command
%whos ndarray

Variable        Type       Data/Info
------------------------------------
GPAS            ndarray    5: 5 elems, type `float64`, 40 bytes
students_gpas   ndarray    3x4: 12 elems, type `float16`, 24 bytes
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [134]:
# NumPy special command for info ~%whos
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7feaa512b200
byteorder:  little
byteswap:  False
type: float16


In [135]:
# Access a particular student GPA
students_gpas[2]

array([2.  , 3.44, 3.69, 4.  ], dtype=float16)