In [244]:
# Intro Numpy
# TeamTreeHouse.com notes 

In [245]:
import numpy as np
np.__version__

'1.16.4'

In [246]:
# Initiate GPA with list of values
GPA = [4.0, 3.2, 3.69, 3.92]
GPA

[4.0, 3.2, 3.69, 3.92]

In [247]:
# Add new GPA data to the end of the list
GPA.append(3.95)
GPA

[4.0, 3.2, 3.69, 3.92, 3.95]

In [248]:
# Initialize study_minutes with 100s zeros using np.zeros
# We are only storing positive values and zeros so we are using unsigned-int16.
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [249]:
# %whos: A special Jupyter Notebook command
%whos

Variable             Type           Data/Info
---------------------------------------------
GPA                  list           n=5
GPAS                 ndarray        5: 5 elems, type `float64`, 40 bytes
fake_log             ndarray        100: 100 elems, type `uint16`, 200 bytes
first_day_minutes    uint16         170
fourth_day_minutes   uint16         60
index                ndarray        2x2: 4 elems, type `int64`, 32 bytes
np                   module         <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
rand                 RandomState    <mtrand.RandomState object at 0x111a7ae58>
second_day_minutes   uint16         75
students_gpas        ndarray        3x4: 12 elems, type `float16`, 24 bytes
study_minutes        ndarray        100: 100 elems, type `uint16`, 200 bytes
third_day_minutes    uint16         44


In [250]:
# Add data to the top of the list
study_minutes[0] = 170

In [251]:
first_day_minutes = study_minutes[0]
first_day_minutes

170

In [252]:
# Add data to the second on the lsit
study_minutes[1] = 75
second_day_minutes = study_minutes[1]
second_day_minutes

75

In [253]:
study_minutes[2] = 44
third_day_minutes = study_minutes[2]
third_day_minutes

44

In [254]:
study_minutes[3] = 60
fourth_day_minutes = study_minutes[3]
fourth_day_minutes

60

In [255]:
# Create n-dimensional array
students_gpas = np.array([
    [4.3, 3.23, 3.69, 3.92],
    [3.72, 2.2, 3.74, 3.89],
    [2.0, 3.44, 3.69, 4.0]
], np.float16)
students_gpas

array([[4.3 , 3.23, 3.69, 3.92],
       [3.72, 2.2 , 3.74, 3.89],
       [2.  , 3.44, 3.69, 4.  ]], dtype=float16)

In [256]:
# 2 dimensional - Rows * Columns
students_gpas.ndim

2

In [257]:
# Matrix shape. X-axis(rows) and Y-axis(column)
students_gpas.shape

(3, 4)

In [258]:
# All of the total element
students_gpas.size

12

In [259]:
# Total student... rows
len(students_gpas)

3

In [260]:
# %whos: A special Jupyter Notebook command
%whos ndarray

Variable        Type       Data/Info
------------------------------------
GPAS            ndarray    5: 5 elems, type `float64`, 40 bytes
fake_log        ndarray    100: 100 elems, type `uint16`, 200 bytes
index           ndarray    2x2: 4 elems, type `int64`, 32 bytes
students_gpas   ndarray    3x4: 12 elems, type `float16`, 24 bytes
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


In [261]:
# NumPy special command for info ~%whos
np.info(students_gpas)

class:  ndarray
shape:  (3, 4)
strides:  (8, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7feaa2d9ff80
byteorder:  little
byteswap:  False
type: float16


In [262]:
# Access a particular student GPA
students_gpas[2]

array([2.  , 3.44, 3.69, 4.  ], dtype=float16)

In [263]:
# Create 2nd dim array
study_minutes = np.array([
    
    study_minutes,
    np.zeros(100, np.uint16)
])
study_minutes.shape

(2, 100)

In [264]:
# Add a data to the 2nd dim array. 
study_minutes[1][0] = 90 #[1] for the 2nd array, and [0] for the first array of second array.
study_minutes

array([[170,  75,  44,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [265]:
# Another way to add data in N-DIM array
# Its just a Tuple[(1,1)]
study_minutes[1,1] = 75 # same as study_minutes[1][1] = 60
study_minutes

array([[170,  75,  44,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 90,  75,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [266]:
# Random number generator
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log
fake_log[[3,8]]

array([44, 50], dtype=uint16)

In [267]:
index = np.array([
    [3,8],
    [0,1]
])

fake_log[index]

array([[ 44,  50],
       [132, 122]], dtype=uint16)

In [268]:
# Append fake_log data into study_minutes

study_minutes = np.append(study_minutes, [fake_log], axis=0)

In [270]:
study_minutes[1,2] = 65
study_minutes

array([[170,  75,  44,  60,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 90,  75,  65,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [273]:
fake_log > 60

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True])

In [275]:
fake_log[fake_log > 30]

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [284]:
study_minutes[(study_minutes < 60) & (study_minutes > 0)]

array([44, 44, 50, 31, 56, 31, 50, 49, 51, 44, 31, 59, 50, 47, 43, 38, 52,
       31, 57, 37, 58], dtype=uint16)

In [291]:
np.array([True, False, True]) & np.array([False, False, True])

array([False, False,  True])

In [ ]:
# SLICING - Any slicing of ndarray returns a view and not a copy

In [292]:
fruit = ["apple", "banana", "cherry", "durian"]

In [294]:
fruit[1:2]

['banana']

In [296]:
fruit[1:3]

['banana', 'cherry']

In [298]:
fruit[:3]

['apple', 'banana', 'cherry']

In [300]:
fruit[1:]

['banana', 'cherry', 'durian']

In [302]:
fruit[2:]

['cherry', 'durian']

In [304]:
fruit[:2]

['apple', 'banana']

In [306]:
fruit[-1]

'durian'

In [308]:
fruit[-2]

'cherry'

In [310]:
fruit[:0]

[]

In [311]:
fruit[-3:]

['banana', 'cherry', 'durian']

In [312]:
fruit[-2:]

['cherry', 'durian']

In [314]:
fruit[:-2]

['apple', 'banana']

In [315]:
fruit[:]

['apple', 'banana', 'cherry', 'durian']

In [317]:
copiedFruit = fruit[:]

In [322]:
copiedFruit[3] = "cheese" # Slicing a list returns a copy

[fruit, copiedFruit]

[['apple', 'banana', 'cherry', 'durian'],
 ['apple', 'banana', 'cherry', 'cheese']]

In [326]:
# Step by 2
fruit[::2]

['apple', 'cherry']

In [328]:
# Negative to walk backwards
fruit[::-1]

['durian', 'cherry', 'banana', 'apple']

In [381]:
# np.arange, 0 Index based

np.arange(42)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [336]:
# practice.shape changes the data permanently

practice = np.arange(42)
practice.shape = (7,6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [341]:
practice[2,1]

13

In [342]:
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [343]:
practice[2:5, 3]

array([15, 21, 27])

In [345]:
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [347]:
practice[2:5, 3::2]

array([[15, 17],
       [21, 23],
       [27, 29]])

In [350]:
practice[2:5, ::3]

array([[12, 15],
       [18, 21],
       [24, 27]])

In [352]:
practice[2:5, 1::3]

array([[13, 16],
       [19, 22],
       [25, 28]])

In [357]:
# Data VIEWS
# Any slicing of ndarray returns a view and not a copy

not_copied = practice[:]
not_copied[0,0] = 101010

not_copied, practice

(array([[101010,      1,      2,      3,      4,      5],
        [     6,      7,      8,      9,     10,     11],
        [    12,     13,     14,     15,     16,     17],
        [    18,     19,     20,     21,     22,     23],
        [    24,     25,     26,     27,     28,     29],
        [    30,     31,     32,     33,     34,     35],
        [    36,     37,     38,     39,     40,     41]]),
 array([[101010,      1,      2,      3,      4,      5],
        [     6,      7,      8,      9,     10,     11],
        [    12,     13,     14,     15,     16,     17],
        [    18,     19,     20,     21,     22,     23],
        [    24,     25,     26,     27,     28,     29],
        [    30,     31,     32,     33,     34,     35],
        [    36,     37,     38,     39,     40,     41]]))

In [359]:
practice.base is None

True

In [361]:
not_copied.base is None

False

In [364]:
not_copied.base is practice

True

In [365]:
practice.flags['OWNDATA'], not_copied.flags['OWNDATA']

(True, False)

In [372]:
# Slicing returns a data view and first_couple.base is actually high_scores

high_scores = np.array(
    [1247700, 1234200, 1218000, 1206800, 1143100]
)
first_couple = high_scores[:2]
first_couple

array([1247700, 1234200])

In [374]:
# By setting the shape properly, the data is changed permanently

first_couple[0] = 8675309
first_couple[0]

8675309

In [377]:
first_couple

array([8675309, 1234200])

In [380]:
# Slicing
# Get the values of only the second and fourth quarters for only the first two years.

quarterly_revenue_by_year = np.array([
    [22.72, 29.13, 25.36, 35.75],
    [29.13, 30.4, 32.71, 43.74],
    [35.71, 37.96, 43.74, 60.5]
])

quarterly_revenue_by_year[:2, 1::2]

array([[29.13, 35.75],
       [30.4 , 43.74]])